(*
 * strategy43.sml, a sample knuth_tree for Assignment 9
 *
 * Rett Bull
 * Computer Science 52
 * August 14, 2017
 *)

(* First, a check to see if the parameters match. *)
val _ = if (colorCount, pegCount) = (4,3)
           then ()
           else (print "\nSize mismatch!!\n";
                 raise InternalInconsistency);

(* Then, the tree. *)
val strategy43 =
  Step
    ([Red,Orange,Yellow],
     [Step ([Green,Green,Green],[Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),
      Step
        ([Red,Yellow,Green],
         [Lose,
          Step
            ([Orange,Green,Orange],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,
              Step
                ([Green,Green,Orange],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Win]),
          Step
            ([Green,Red,Red],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,
              Step
                ([Green,Green,Red],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Win]),Lose,
          Step
            ([Orange,Green,Green],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),
          Step
            ([Yellow,Green,Green],
             [Lose,Lose,Lose,Lose,Lose,
              Step
                ([Green,Red,Green],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,Win]),
          Lose,
          Step
            ([Yellow,Yellow,Green],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,
              Step
                ([Green,Yellow,Green],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Win]),Lose]),
      Step
        ([Red,Red,Green],
         [Step
            ([Orange,Yellow,Orange],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,
              Step
                ([Yellow,Yellow,Orange],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Win]),
          Step
            ([Yellow,Green,Orange],
             [Lose,Lose,Lose,Lose,
              Step
                ([Yellow,Yellow,Red],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,
              Step
                ([Green,Yellow,Orange],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Win]),
          Step
            ([Orange,Green,Red],
             [Lose,Lose,Lose,Lose,Lose,
              Step
                ([Green,Yellow,Red],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,
              Step
                ([Yellow,Green,Red],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Win]),Lose,
          Step
            ([Orange,Red,Orange],
             [Lose,Lose,Lose,Lose,
              Step
                ([Orange,Yellow,Green],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Win]),
          Step
            ([Orange,Red,Red],
             [Lose,Lose,Lose,Lose,Lose,
              Step
                ([Green,Red,Orange],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,
              Step
                ([Yellow,Red,Red],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Win]),Lose,
          Step
            ([Orange,Red,Green],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,
              Step
                ([Yellow,Red,Green],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Win]),Lose]),
      Step
        ([Orange,Yellow,Red],
         [Lose,Lose,Lose,
          Step
            ([Yellow,Red,Orange],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,Lose,
          Lose,Win]),
      Step
        ([Red,Green,Green],
         [Step
            ([Orange,Orange,Orange],
             [Step
                ([Yellow,Yellow,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Lose,Lose,Lose,Lose,Win]),
          Step
            ([Green,Orange,Orange],
             [Lose,Lose,Lose,Lose,
              Step
                ([Green,Yellow,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Win]),Lose,Lose,
          Step
            ([Orange,Orange,Green],
             [Step
                ([Red,Red,Red],[Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),
              Step
                ([Yellow,Green,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Lose,Lose,Lose,Win]),
          Step
            ([Green,Orange,Green],
             [Lose,Lose,Lose,Lose,Lose,
              Step
                ([Green,Green,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,Win]),
          Lose,
          Step
            ([Red,Red,Green],
             [Lose,Lose,Lose,Lose,Lose,Lose,
              Step
                ([Red,Green,Red],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Win]),
          Win]),
      Step
        ([Red,Orange,Green],
         [Lose,
          Step
            ([Orange,Yellow,Yellow],
             [Lose,Lose,Lose,Lose,Lose,
              Step
                ([Yellow,Red,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,Win]),
          Step
            ([Orange,Green,Yellow],
             [Lose,Lose,Lose,Lose,Lose,
              Step
                ([Green,Red,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,Win]),
          Lose,
          Step
            ([Red,Yellow,Red],
             [Lose,
              Step
                ([Yellow,Orange,Orange],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Lose,Lose,Lose,Win]),
          Step
            ([Red,Red,Orange],
             [Lose,Lose,
              Step
                ([Orange,Orange,Red],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Lose,Lose,Win]),
          Step
            ([Red,Green,Orange],
             [Lose,Lose,Lose,
              Step
                ([Green,Orange,Red],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Lose,Win]),
          Step
            ([Red,Yellow,Green],
             [Lose,Lose,Lose,Lose,Lose,
              Step
                ([Yellow,Orange,Green],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,Win]),
          Lose]),
      Step
        ([Red,Red,Orange],
         [Lose,Lose,
          Step
            ([Yellow,Orange,Red],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
          Step
            ([Orange,Red,Yellow],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,
          Step
            ([Red,Yellow,Orange],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose]),
      Step
        ([Red,Red,Green],
         [Step
            ([Orange,Orange,Yellow],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,
              Step
                ([Yellow,Orange,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Win]),
          Step
            ([Green,Orange,Yellow],
             [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
          Step
            ([Red,Orange,Orange],
             [Lose,Lose,Lose,Lose,
              Step
                ([Red,Yellow,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Win]),
          Step
            ([Red,Orange,Red],
             [Lose,Lose,Lose,Lose,
              Step
                ([Red,Green,Yellow],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Win]),Lose,
          Step
            ([Red,Red,Yellow],
             [Lose,Lose,Lose,Lose,
              Step
                ([Red,Orange,Green],
                 [Lose,Lose,Lose,Lose,Lose,Lose,Lose,Lose,Win]),Lose,Lose,
              Lose,Win]),Lose]),Win]);